name: Deploy STAGING

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Deploy para STAGING
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.FTP_SERVER_STAGING }}
          ftp_username: ${{ secrets.FTP_USERNAME_STAGING }}
          ftp_password: ${{ secrets.FTP_PASSWORD_STAGING }}
          local_source_dir: "./"
          dist_target_dir: "/www/stage/cliente1/"
          exclude: |
            ^\.git$
            ^\.git/
            ^node_modules/
            \.gitignore
